FPS: 1.0
MENU_HEIGHT: 0.6
MENU_WIDTH: 0.4
STORE_HEIGHT: 0.6
STORE_WIDTH: 0.4
GAME_HEIGHT: 1.0
GAME_WIDTH: 1.0
INVENTORY_HEIGHT: 0.6
INVENTORY_WIDTH: 0.4
MAX_FLOOR_SIZE: 6.0
MAX_ROOM_SIZE: 12.0
FOV: 10.0