FPS: 60.0
MENU_HEIGHT: 0.6
MENU_WIDTH: 0.4
STORE_HEIGHT: 0.6
STORE_WIDTH: 0.4
GAME_HEIGHT: 0.6
GAME_WIDTH: 0.4
INVENTORY_HEIGHT: 0.6
INVENTORY_WIDTH: 0.4
MAX_FLOOR_SIZE: 5.0
MIN_FLOOR_SIZE: 4.0
MAX_ROOM_SIZE: 12.0
MIN_ROOM_SIZE: 8.0
RENDER_DISTANCE: 40.0
ZOOM: 20.0